version: "3"
services:

  jupyter:
    image: jupyter/datascience-notebook
    ports:
      - "8888:8888"
    links:
      - postgres
    volumes:
      - "./work:/home/jovyan/work"

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: data
      POSTGRES_PASSWORD: data
      POSTGRES_DB: data
